// packages/react/src/components/Button.tsx
import React from 'react'
import { createReactWrapper, type WebComponentProps } from '../utils/createReactWrapper.js'

export interface ButtonProps extends WebComponentProps {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  loading?: boolean
  disabled?: boolean
  href?: string
  target?: string
  rel?: string
  type?: 'button' | 'submit' | 'reset'
  onClick?: (event: Event) => void
}

const eventMap = {
  onClick: 'click'
}

const MzButton = createReactWrapper<HTMLElement>('mz-button', eventMap)

export const Button = MzButton as React.ForwardRefExoticComponent<ButtonProps>

Button.displayName = 'Button'

// packages/svelte/src/lib/Button.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  
  // Props
export let variant = 'primary';
export let size = 'md';
export let loading = false;
export let disabled = false;
export let href= undefined;
export let target= undefined;
export let rel= undefined;
export let type = 'button';

  // Event dispatcher
  const dispatch = createEventDispatcher<{
    click: MouseEvent
  }>();

  // Reactive attributes
  $: attrs = {
    'variant': variant,
    'size': size,
    'loading': loading,
    'disabled': disabled,
    'href': href,
    'target': target,
    'rel': rel,
    'type': type
  };
</script>

<mz-button
  {...attrs}
      on:click={(event) => dispatch('click', event)}
>
  <slot />
</mz-button>
